<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="Current">
  <PropertyGroup>
    <Authors>John Taylor</Authors>
    <DefaultLanguage>en-US</DefaultLanguage>
    <DocumentationFile>..\docs\$(MSBuildProjectName).xml</DocumentationFile>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <ErrorReport>send</ErrorReport>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>preview</LangVersion>
    <NeutralLanguage>en-US</NeutralLanguage>
    <NuGetAuditLevel>low</NuGetAuditLevel>
    <NuGetAuditMode>all</NuGetAuditMode>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <RepositoryType>git</RepositoryType>
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    <WarningLevel>9999</WarningLevel>
  </PropertyGroup>
</Project>