<Project>
	<PropertyGroup>
		<Deterministic>true</Deterministic>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<ErrorReport>send</ErrorReport>
		<ImplicitUsings>disable</ImplicitUsings>
		<LangVersion>preview</LangVersion>
		<NeutralLanguage>en-US</NeutralLanguage>
		<NuGetAuditLevel>low</NuGetAuditLevel>
		<NuGetAuditMode>all</NuGetAuditMode>
		<Nullable>enable</Nullable>
		<RepositoryType>git</RepositoryType>
		<WarningLevel>9999</WarningLevel>
	</PropertyGroup>
</Project>