<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AnalysisLevel>preview-all</AnalysisLevel>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
    <Deterministic>true</Deterministic>
    <DocumentationFile>..\docs\$(AssemblyName).xml</DocumentationFile>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <ErrorReport>send</ErrorReport>
    <ImplicitUsings>disable</ImplicitUsings>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Nullable>enable</Nullable>
    <TargetFramework>net11.0</TargetFramework>
    <WarningLevel>9999</WarningLevel>
    <LangVersion>preview</LangVersion>
    <Platforms>AnyCPU;x86;x64</Platforms>
    <Title>ZScript Specification</Title>
    <RepositoryType>git</RepositoryType>
    <AssemblyVersion>1.0.0.1</AssemblyVersion>
    <FileVersion>1.0.0.1</FileVersion>
    <IncludeSymbols>False</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <FileAlignment>512</FileAlignment>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Parser\Parser.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="MapInfo\" />
    <Folder Include="UDMF\" />
  </ItemGroup>

</Project>
