<?xml version="1.0" encoding="utf-8"?>
<xs:schema
  attributeFormDefault="unqualified"
  elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:tr="Parser/TokenRule"
  xmlns:sp="Parser/Spec"
  xml:lang="en-us"
  targetNamespace="Parser/Spec">
  
  <xs:simpleType name="NoSlashesStringType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[^\\/]*" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="ComparisonType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="StartsWith" />
      <xs:enumeration value="EndsWith" />
      <xs:enumeration value="Contains" />
      <xs:enumeration value="Equals" />
      <xs:enumeration value="DoesNotEqual" />
      <xs:enumeration value="DoesNotContain" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="HeaderStringType">
    <xs:restriction base="xs:token">
      <xs:maxLength value="8"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="FileNameType" mixed="false">
    <xs:simpleContent>
      <xs:extension base="sp:NoSlashesStringType">
        <xs:attribute name="ComparisonType" type="sp:ComparisonType" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <xs:complexType name="FormatType">
    <xs:sequence>
      <xs:element name="FileExt" minOccurs="0" maxOccurs="unbounded" type="xs:token" />
      <xs:element name="FileHeader" minOccurs="0" maxOccurs="unbounded" type="sp:HeaderStringType" />
      <xs:element name="FileName" minOccurs="0" maxOccurs="unbounded" type="sp:FileNameType" />
      <xs:element name="FileSize" minOccurs="0" maxOccurs="unbounded" type="xs:normalizedString" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:token" />
  </xs:complexType>
  
  <xs:element name="Formats">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Format" minOccurs="0" maxOccurs="unbounded" type="sp:FormatType" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>