<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net11.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Parser\Parser.csproj" />
    <ProjectReference Include="..\Specification.INI\Specification.INI.csproj" />
    <ProjectReference Include="..\Specification.IPL\Specification.IPL.csproj" />
    <ProjectReference Include="..\Specification.JSON\Specification.JSON.csproj" />
    <ProjectReference Include="..\Specification.REG\Specification.REG.csproj" />
    <ProjectReference Include="..\Specification.WAD\Specification.WAD.csproj" />
    <ProjectReference Include="..\Specification.XML\Specification.XML.csproj" />
    <ProjectReference Include="..\Specification.ZDoom\Specification.ZDoom.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="MainForm.Designer.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>