<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <AnalysisLevel>preview-all</AnalysisLevel>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <TargetFramework>net11.0</TargetFramework>
    <Platforms>AnyCPU;x86;x64</Platforms>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
    <PackageReference Include="Roslynator.Analyzers" Version="4.15.0" />
    <PackageReference Include="Roslynator.CodeAnalysis.Analyzers" Version="4.15.0" />
    <PackageReference Include="Roslynator.CSharp" Version="4.15.0" />
    <PackageReference Include="Roslynator.CSharp.Workspaces" Version="4.15.0" />
    <PackageReference Include="Roslynator.Formatting.Analyzers" Version="4.15.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0-pre.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="4.0.0-pre.81" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <!-- <ProjectReference Include="..\..\Plant VNC\VNCChecker.csproj" /> -->
    <ProjectReference Include="..\Common\Common.csproj" />
    <!-- <ProjectReference Include="..\FormObjectViewer\FormObjectViewer.csproj" /> -->
    <ProjectReference Include="..\Parser\Parser.csproj" />
    <ProjectReference Include="..\Specification.INI\Specification.INI.csproj" />
    <ProjectReference Include="..\Specification.IPL\Specification.IPL.csproj" />
    <ProjectReference Include="..\Specification.JSON\Specification.JSON.csproj" />
    <ProjectReference Include="..\Specification.REG\Specification.REG.csproj" />
    <ProjectReference Include="..\Specification.WAD\Specification.WAD.csproj" />
    <ProjectReference Include="..\Specification.XML\Specification.XML.csproj" />
    <ProjectReference Include="..\Specification.ZDoom\Specification.ZDoom.csproj" />
    <!-- <ProjectReference Include="..\TestConsole\TestConsole.csproj" /> -->
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
