<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AnalysisLevel>preview-all</AnalysisLevel>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
    <Deterministic>true</Deterministic>
    <DocumentationFile>..\docs\$(AssemblyName).xml</DocumentationFile>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <ErrorReport>send</ErrorReport>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>preview</LangVersion>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x86;x64</Platforms>
    <TargetFramework>net11.0</TargetFramework>
    <WarningLevel>9999</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Parser\Parser.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
