<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AnalysisLevel>preview-all</AnalysisLevel>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
    <Deterministic>true</Deterministic>
    <DocumentationFile>..\docs\$(AssemblyName).xml</DocumentationFile>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <ErrorReport>send</ErrorReport>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>preview</LangVersion>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x86;x64</Platforms>
    <TargetFramework>net11.0</TargetFramework>
    <WarningLevel>9999</WarningLevel>
    <Title>XML Format Specification</Title>
    <PackageIcon>XMLFile.ico</PackageIcon>
    <ApplicationIcon>CPPXMLProject.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="CPPXMLProject.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\..\..\Icons\XMLFile.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Parser\Parser.csproj" />
  </ItemGroup>

</Project>
