<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AnalysisLevel>preview-all</AnalysisLevel>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
    <DocumentationFile>..\docs\$(AssemblyName).xml</DocumentationFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Platforms>AnyCPU;x86;x64</Platforms>
    <TargetFramework>net11.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.AnalyzerUtilities" Version="5.0.0-1.25277.114" />
    <PackageReference Include="Roslynator.Analyzers" Version="4.15.0" />
    <PackageReference Include="Roslynator.CodeAnalysis.Analyzers" Version="4.15.0" />
    <PackageReference Include="Roslynator.CodeFixes" Version="4.15.0" />
    <PackageReference Include="Roslynator.Formatting.Analyzers" Version="4.15.0" />
    <PackageReference Include="Roslynator.CSharp" Version="4.15.0" />
    <PackageReference Include="Roslynator.CSharp.Workspaces" Version="4.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Parser\Parser.csproj" />
  </ItemGroup>

  <ProjectExtensions>
    <VisualStudio>
      <UserProperties schemas_4terminal_x0020_settings_1json__JsonSchema="https://www.schemastore.org/jsonld.json" />
    </VisualStudio>
  </ProjectExtensions>

</Project>
