<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AnalysisLevel>preview-all</AnalysisLevel>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
    <DocumentationFile>..\docs\$(AssemblyName).xml</DocumentationFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TargetFramework>net11.0</TargetFramework>
    <Platforms>AnyCPU;x86;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Parser\Parser.csproj" />
  </ItemGroup>

  <ProjectExtensions>
    <VisualStudio>
      <UserProperties schemas_4terminal_x0020_settings_1json__JsonSchema="https://www.schemastore.org/jsonld.json" />
    </VisualStudio>
  </ProjectExtensions>

</Project>
