<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AnalysisLevel>preview-all</AnalysisLevel>
    <DefaultLanguage>en-US</DefaultLanguage>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NuGetAuditLevel>low</NuGetAuditLevel>
    <NuGetAuditMode>all</NuGetAuditMode>
    <Platforms>AnyCPU;x86;x64</Platforms>
    <TargetFramework>net11.0</TargetFramework>
    <UserSecretsId>37d036cf-7713-4a90-a266-751a9fd18f93</UserSecretsId>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="V2\" />
    <EmbeddedResource Remove="V2\" />
    <None Remove="V2\" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Samples\demon.zs" />
    <Content Include="Samples\label.ipl" />
    <Content Include="Samples\sample.cfg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.AnalyzerUtilities" Version="5.0.0-1.25277.114" />
    <PackageReference Include="Roslynator.Analyzers" Version="4.15.0" />
    <PackageReference Include="Roslynator.CodeAnalysis.Analyzers" Version="4.15.0" />
    <PackageReference Include="Roslynator.CodeFixes" Version="4.15.0" />
    <PackageReference Include="Roslynator.Formatting.Analyzers" Version="4.15.0" />
    <PackageReference Include="Roslynator.CSharp" Version="4.15.0" />
    <PackageReference Include="Roslynator.CSharp.Workspaces" Version="4.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
  </ItemGroup>

</Project>
