<?xml version="1.0" encoding="utf-8"?>
<xs:schema
  targetNamespace="Parser/Operation"
  attributeFormDefault="qualified"
  elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:op="Parser/Operation"
  xml:lang="en-us">

  <xs:attributeGroup name="LengthAttrGroup">
    <xs:attribute name="length" type="xs:positiveInteger"/>
    <xs:attribute name="length_var" type="xs:token"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="PositionAttrGroup">
    <xs:attribute name="position" type="xs:nonNegativeInteger"/>
    <xs:attribute name="position_var" type="xs:token"/>
  </xs:attributeGroup>

  <xs:group name="Command">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
      
      </xs:choice>
    </xs:sequence>
  </xs:group>

  <xs:element name="GotoOpIndex"> <!-- substitutionGroup="op:Command" -->
    <xs:complexType>
      <!-- <xs:group ref="op:AnyOperation" maxOccurs="unbounded"/> -->
    </xs:complexType>
  </xs:element>

</xs:schema>