<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="Parser/Spec" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="Parser/Spec">
  <xs:include schemaLocation="Types.xsd"/>
  <xs:complexType name="FileInferencesType">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="And" type="FileInferencesType"/>
        <xs:element name="Or" type="FileInferencesType"/>
        <xs:element name="Header">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute default="4" name="length" use="optional" type="xs:int"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="Extension" type="NonEmptyTokenType"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="initial" type="AndOrType" default="or"/>
  </xs:complexType>
  <xs:element name="Specs">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Spec" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="NonEmptyTokenType"/>
              <xs:element name="TextFile" type="xs:boolean"/>
              <xs:element name="TokenRules" type="RuleList" minOccurs="0"/>
              <xs:element name="GroupTokenRules" type="RuleList" minOccurs="0"/>
              <xs:element name="TokenLookups" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="TokenLookup" type="TokenLookupType" minOccurs="0" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element ref="Instructions" minOccurs="0"/>
              <xs:element name="FileInferences" minOccurs="0" type="FileInferencesType"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
