<?xml version="1.0" encoding="utf-8"?>
<xs:schema
  targetNamespace="Parser/TokenRule"
  attributeFormDefault="qualified"
  elementFormDefault="qualified"
  xmlns:tr="Parser/TokenRule"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  
  <xs:simpleType name="RuleTypeToken">
    <xs:restriction base="xs:token">

      <xs:enumeration value="None"/>

      <!-- Token Rule Types -->
      <xs:enumeration value="Competitive"/>
      <xs:enumeration value="TokenMatch"/>
      <xs:enumeration value="TokenExact"/>
      <xs:enumeration value="TokenExtract"/>
      <xs:enumeration value="ErrorMatch"/>
      <xs:enumeration value="SplitMatch"/>
      <xs:enumeration value="SplitExact"/>
      <xs:enumeration value="StoreExtra"/>
      <xs:enumeration value="StoreOther"/>

      <!-- Combos -->
      <xs:enumeration value="ThrowMatch"/> <!-- IgnoredToken & TokenMatch -->
      <xs:enumeration value="TokenComment"/> <!-- IgnoredToken & Competitive -->
    
      <!-- Flags -->
      <xs:enumeration value="IgnoreCase"/>
      <xs:enumeration value="IgnoredToken"/>
      <xs:enumeration value="Opt"/>
      <xs:enumeration value="Mult"/>
      <xs:enumeration value="Recursive"/>
      <xs:enumeration value="Any"/> <!-- Opt & Mult -->
    
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="RuleTypeList">
    <xs:list itemType="tr:RuleTypeToken"/>
  </xs:simpleType>
  
  

  <xs:complexType name="RuleDef">
    <xs:all>
      <xs:element name="TypeToAssign" minOccurs="0" maxOccurs="1" type="xs:token" default="None"/>
      <xs:element name="Type" type="tr:RuleTypeList" minOccurs="1" maxOccurs="1"/>
      <xs:element name="Data" minOccurs="0" maxOccurs="1" default="" type="xs:string"/>
    </xs:all>
    <xs:attribute name="name" type="xs:token"/>
  </xs:complexType>

  <xs:complexType name ="RuleList">
    <xs:sequence>
      <xs:element name="Rule" type="tr:RuleDef" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="TokenRules" type="tr:RuleList"/>
  <xs:element name="GroupTokenRules" type="tr:RuleList"/>
  
  

</xs:schema>
