//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace ExcelSequenceHelper {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(1)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class KeySheet : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        internal Microsoft.Office.Tools.Excel.ListObject KeyTable;
        
        internal Microsoft.Office.Tools.Excel.ListObject BoolTable;
        
        internal Microsoft.Office.Tools.Excel.ListObject YNTable;
        
        internal Microsoft.Office.Tools.Excel.ListObject SizeOverrideTable;
        
        internal Microsoft.Office.Tools.Excel.ListObject FontTable;
        
        internal Microsoft.Office.Tools.Excel.ListObject TableTypeTable;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Bool;
        
        internal Microsoft.Office.Tools.Excel.NamedRange CellFontSize_Override;
        
        internal Microsoft.Office.Tools.Excel.NamedRange HeaderFontSize_Override;
        
        internal Microsoft.Office.Tools.Excel.NamedRange StyleNames;
        
        internal Microsoft.Office.Tools.Excel.NamedRange TitleFontSize_Override;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "18.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public KeySheet(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "KeySheet", "KeySheet") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "18.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.KeySheet = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "18.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "18.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "18.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "18.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "18.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "18.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.KeyTable.BeginInit();
            this.BoolTable.BeginInit();
            this.YNTable.BeginInit();
            this.SizeOverrideTable.BeginInit();
            this.FontTable.BeginInit();
            this.TableTypeTable.BeginInit();
            this.Bool.BeginInit();
            this.CellFontSize_Override.BeginInit();
            this.HeaderFontSize_Override.BeginInit();
            this.StyleNames.BeginInit();
            this.TitleFontSize_Override.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "18.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.TitleFontSize_Override.EndInit();
            this.StyleNames.EndInit();
            this.HeaderFontSize_Override.EndInit();
            this.CellFontSize_Override.EndInit();
            this.Bool.EndInit();
            this.TableTypeTable.EndInit();
            this.FontTable.EndInit();
            this.SizeOverrideTable.EndInit();
            this.YNTable.EndInit();
            this.BoolTable.EndInit();
            this.KeyTable.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "18.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.KeyTable = Globals.Factory.CreateListObject(null, null, "KeySheet:KeyTable", "KeyTable", this);
            this.BoolTable = Globals.Factory.CreateListObject(null, null, "KeySheet:BoolTable", "BoolTable", this);
            this.YNTable = Globals.Factory.CreateListObject(null, null, "KeySheet:YNTable", "YNTable", this);
            this.SizeOverrideTable = Globals.Factory.CreateListObject(null, null, "KeySheet:SizeOverrideTable", "SizeOverrideTable", this);
            this.FontTable = Globals.Factory.CreateListObject(null, null, "KeySheet:FontTable", "FontTable", this);
            this.TableTypeTable = Globals.Factory.CreateListObject(null, null, "KeySheet:TableTypeTable", "TableTypeTable", this);
            this.Bool = Globals.Factory.CreateNamedRange(null, null, "Bool", "Bool", this);
            this.CellFontSize_Override = Globals.Factory.CreateNamedRange(null, null, "CellFontSize_Override", "CellFontSize_Override", this);
            this.HeaderFontSize_Override = Globals.Factory.CreateNamedRange(null, null, "HeaderFontSize_Override", "HeaderFontSize_Override", this);
            this.StyleNames = Globals.Factory.CreateNamedRange(null, null, "StyleNames", "StyleNames", this);
            this.TitleFontSize_Override = Globals.Factory.CreateNamedRange(null, null, "TitleFontSize_Override", "TitleFontSize_Override", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "18.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "18.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.TitleFontSize_Override.Dispose();
            this.StyleNames.Dispose();
            this.HeaderFontSize_Override.Dispose();
            this.CellFontSize_Override.Dispose();
            this.Bool.Dispose();
            this.TableTypeTable.Dispose();
            this.FontTable.Dispose();
            this.SizeOverrideTable.Dispose();
            this.YNTable.Dispose();
            this.BoolTable.Dispose();
            this.KeyTable.Dispose();
            base.OnShutdown();
        }
    }
    
    internal sealed partial class Globals {
        
        private static KeySheet _KeySheet;
        
        internal static KeySheet KeySheet {
            get {
                return _KeySheet;
            }
            set {
                if ((_KeySheet == null)) {
                    _KeySheet = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
