<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AnalysisLevel>preview-all</AnalysisLevel>
    <ApplicationIcon>Icons\ActiveServerApplication.ico</ApplicationIcon>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
    <Deterministic>True</Deterministic>
    <DocumentationFile>..\docs\$(AssemblyName).xml</DocumentationFile>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <ErrorReport>send</ErrorReport>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>preview</LangVersion>
    <NeutralLanguage>en-US</NeutralLanguage>
    <NuGetAuditLevel>low</NuGetAuditLevel>
    <NuGetAuditMode>all</NuGetAuditMode>
    <Nullable>enable</Nullable>
    <OutputType>WinExe</OutputType>
    <Platforms>AnyCPU;x86;x64</Platforms>
    <StartupObject>FormObjectViewer.Program</StartupObject>
    <TargetFramework>net11.0-windows</TargetFramework>
    <Title>Form Based Object Browser</Title>
    <UseWindowsForms>true</UseWindowsForms>
    <WarningLevel>9999</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <COMReference Include="Shell32">
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>50a7e9b0-70ef-11d1-b75a-00a0c90564fe</Guid>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
    <COMReference Include="MSXML2">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>6</VersionMajor>
      <Guid>f5078f18-c551-11d3-89b9-0000f81fe221</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Icons\ActiveServerApplication.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Console.Menu\Terminal.Menu.csproj" />
    <ProjectReference Include="..\Parser.Forms\Parser.Forms.csproj" />
    <ProjectReference Include="..\Parser\Parser.csproj" />
    <ProjectReference Include="..\Specification.INI\Specification.INI.csproj" />
    <ProjectReference Include="..\Specification.IPL\Specification.IPL.csproj" />
    <ProjectReference Include="..\Specification.JSON\Specification.JSON.csproj" />
    <ProjectReference Include="..\Specification.MapInfo\Specification.MapInfo.csproj" />
    <ProjectReference Include="..\Specification.REG\Specification.REG.csproj" />
    <ProjectReference Include="..\Specification.WAD\Specification.WAD.csproj" />
    <ProjectReference Include="..\Specification.XML\Specification.XML.csproj" />
    <ProjectReference Include="..\Specification.ZScript\Specification.ZDoom.csproj" />
    <!-- <ProjectReference Include="..\TestConsole\TestConsole.csproj" /> -->
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>