<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AnalysisLevel>preview-all</AnalysisLevel>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Platforms>AnyCPU;x86;x64</Platforms>
    <TargetFramework>net11.0-windows</TargetFramework>
    <UserSecretsId>37d036cf-7713-4a90-a266-751a9fd18f93</UserSecretsId>
    <Version>1.0.0</Version>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.AnalyzerUtilities" Version="5.0.0-1.25277.114" />
    <PackageReference Include="Roslynator.Analyzers" Version="4.15.0" />
    <PackageReference Include="Roslynator.Formatting.Analyzers" Version="4.15.0" />
    <PackageReference Include="Roslynator.CSharp" Version="4.15.0" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Parser\Parser.csproj" />
  </ItemGroup>

</Project>
