//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Paths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        static Paths() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestConsole.Paths", typeof(Paths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParserLib\Specification.WAD\WAD.txt.
        /// </summary>
        public static string binparse_wad {
            get {
                return ResourceManager.GetString("binparse_wad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParserLib\Specification.INI\Samples\default.ini.
        /// </summary>
        public static string ini_vncdefault {
            get {
                return ResourceManager.GetString("ini_vncdefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParserLib\Specification.IPL\Samples\6456 batch.txt.
        /// </summary>
        public static string ipl_batch6456 {
            get {
                return ResourceManager.GetString("ipl_batch6456", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParserLib\Specification.IPL\Samples\6458 batch.txt.
        /// </summary>
        public static string ipl_batch6458 {
            get {
                return ResourceManager.GetString("ipl_batch6458", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParserLib\Parser\Samples\label.ipl.
        /// </summary>
        public static string ipl_label {
            get {
                return ResourceManager.GetString("ipl_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParserLib\Specification.IPL\Samples\simple.txt.
        /// </summary>
        public static string ipl_simple {
            get {
                return ResourceManager.GetString("ipl_simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParserLib\Specification.JSON\Samples\errors.json.
        /// </summary>
        public static string json_error {
            get {
                return ResourceManager.GetString("json_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParserLib\Specification.JSON\Samples\launchSettings.json.
        /// </summary>
        public static string json_launch {
            get {
                return ResourceManager.GetString("json_launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParserLib\Specification.XML\Samples\errors.xml.
        /// </summary>
        public static string xml_errors {
            get {
                return ResourceManager.GetString("xml_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParserLib\Specification.XML\Samples\operation.xml.
        /// </summary>
        public static string xml_operation {
            get {
                return ResourceManager.GetString("xml_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParserLib\Specification.XML\Schemas\specification.xsd.
        /// </summary>
        public static string xsd_specification {
            get {
                return ResourceManager.GetString("xsd_specification", resourceCulture);
            }
        }
    }
}
