//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Paths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Paths() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestConsole.Paths", typeof(Paths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\johntay4\source\repos\Projects\Parser.Text\Samples\sample.acs.
        /// </summary>
        internal static string acs_testscript {
            get {
                return ResourceManager.GetString("acs_testscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\johntay4\source\repos\Projects\UnitTests\process.html.
        /// </summary>
        internal static string html_processfile {
            get {
                return ResourceManager.GetString("html_processfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\johntay4\source\repos\Projects\Parser.Text\Samples\default.ini.
        /// </summary>
        internal static string ini_vncdefault {
            get {
                return ResourceManager.GetString("ini_vncdefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\johntay4\source\repos\Projects\Specification.IPL\Samples\6456 batch.txt.
        /// </summary>
        internal static string ipl_batch6456 {
            get {
                return ResourceManager.GetString("ipl_batch6456", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Johntay4\source\repos\Projects\Parser.Text\Samples\label.ipl.
        /// </summary>
        internal static string ipl_label {
            get {
                return ResourceManager.GetString("ipl_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\johntay4\source\repos\Projects\Parser.Text\Samples\mapinfo.lmp.
        /// </summary>
        internal static string mapinfo_common {
            get {
                return ResourceManager.GetString("mapinfo_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\johntay4\source\repos\Projects\Specification.REG\Resources\Types\ipl.reg.
        /// </summary>
        internal static string reg_iplfile {
            get {
                return ResourceManager.GetString("reg_iplfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\johntay4\source\repos\Projects\Parser.Text\Samples\sndinfo.txt.
        /// </summary>
        internal static string sndinfo_test {
            get {
                return ResourceManager.GetString("sndinfo_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\johntay4\source\repos\Projects\Specification.XML\Schemas\specification.xsd.
        /// </summary>
        internal static string xsd_specification {
            get {
                return ResourceManager.GetString("xsd_specification", resourceCulture);
            }
        }
        
        /// <summary>
        /// Demon zscript file.
        /// </summary>
        internal static string zs_demon {
            get {
                return ResourceManager.GetString("zs_demon", resourceCulture);
            }
        }
    }
}
