//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Specification.REG.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Samples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Samples() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Specification.REG.Properties.Samples", typeof(Samples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParserLib\Specification.REG\Resources\HKEY_Classes_Root\ClassExt.reg.
        /// </summary>
        internal static string reg_classext {
            get {
                return ResourceManager.GetString("reg_classext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParserLib\Specification.REG\Resources\Types\dllfile.reg.
        /// </summary>
        internal static string reg_dllfile {
            get {
                return ResourceManager.GetString("reg_dllfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParserLib\Specification.REG\Resources\Types\ipl.reg.
        /// </summary>
        internal static string reg_ipl {
            get {
                return ResourceManager.GetString("reg_ipl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParserLib\Specification.REG\Resources\Types\ipl.reg.
        /// </summary>
        internal static string reg_iplfile {
            get {
                return ResourceManager.GetString("reg_iplfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParserLib\Specification.REG\querpus.ipl.
        /// </summary>
        internal static string reg_querpus {
            get {
                return ResourceManager.GetString("reg_querpus", resourceCulture);
            }
        }
    }
}
